### ISSUE TITLE
Safely remove drive

### ISSUE THREAD

**Issue by manujchandra** [SL-RU/ranger_udisk_menu#1]
In nautilus there is an option to safely remove drive.

![Screenshot from 2021-06-12 17-32-14](https://user-images.githubusercontent.com/15191493/121775292-5b31d680-cba4-11eb-850e-737e1eede6dc.png)

It powers off the drive (no lights on)

Is there a similar feature in ranger_udisk_menu? Thanks!

**Comment by SL-RU** [comment]
It can be done with comand `udisksctl power-off -b /dev/sdX`, I've added this function right now :smiley:  

You can try it. Key `p` will do the job. I've documented it in the README also
