### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by agenbite** [SL-RU/ranger_udisk_menu#2]
Sorry for the inexpressive title. I've followed the steps to install and when I
call `:mount` the screen flickers and nothing else happens. How can I know if
this is a permissions problem or something else? I've tried calling the program
from command line, but that doesn't work. Thanks in advance!

**Comment by Syphdias** [comment]
@agenbite, maybe not relevant anymore but I had this issue when the window was too small.

**Comment by agenbite** [comment]
Hey, thanks, @Syphdias! Unfortunately that doesn't seem to be my case... :(

**Comment by Syphdias** [comment]
What happens if you execute the menu.py outside of ranger? Probably:
```
python3 ~/.config/ranger/ranger_udisk_menu/menu.py
```

Edit: Just re-read your post, And you sayed you already tried that. I suppose nothing happened?

**Comment by Syphdias** [comment]
What happens if you do `lsblk --all --json -O`?

**Comment by agenbite** [comment]
On Sun Mar 20, 2022 at 2:00 PM CET, Syphdias wrote:
> What happens if you execute the menu.py outside of ranger? Probably:
> ```
> python3 ~/.config/ranger/ranger_udisk_menu/menu.py
> ```
Traceback (most recent call last): File "/home/myself/.config/ranger/ranger_udisk_menu/menu.py", line 230, in <module> sel = cp.select()
File "/home/jlmyself/.config/ranger/ranger_udisk_menu/menu.py", line 165, in select
self._select_print(x)
File "/home/jlmyself/.config/ranger/ranger_udisk_menu/menu.py", line 130, in _select_print
self._select_print_block_device(bd, bd_i)
File "/home/jlmyself/.config/ranger/ranger_udisk_menu/menu.py", line 114, in _select_print_block_device
self.screen.addstr(2 + i, 2, bd['name'] + " " + model + " " + size)
_curses.error: addwstr() returned ERR

**Comment by agenbite** [comment]
On Sun Mar 20, 2022 at 2:06 PM CET, Syphdias wrote:
> What happens if you do `lsblk --all --json -O`?
This: https://paste.sr.ht/~inwit/e53a11d6f25190668229f78b3b28e89e55969a5b

Thank you for your help.

**Comment by Syphdias** [comment]
I used your `lsblk` output, wrote it to a file and read in that file (instead of using my life data). That worked.

If I dropped my window height bellow 65 lines for your data in a mock file – you can check with `echo $LINES`), I did get the same error I also get when the window is too small for my live data.

Since you have a lot of loop devices from your snap installs, I am not yet convinced that your window is big yet (lines-wise that is). Maybe you have a small laptop screen or something. 

Could you try:
1. Fullscreening a terminal window
2. Zooming out (usually <kbd>Ctrl</kbd>-<kbd>+</kbd> in most terminal emulators)
3. and the run: `python3 ~/.config/ranger/ranger_udisk_menu/menu.py; lsblk --all --json -O |grep '"name"' -c; echo $COLUMNS $LINES`

**Comment by Syphdias** [comment]
I just realized that I have a 1440p Monitor which barely fits the requirement of 65 lines (I have 68 on a full height terminal window and 70 on fullscreen). This make me even more certain you still have a space issue.

I think the 65 come from 60 lines devices + 2 lines for explanation + 2 lines for top and bottom border + 1 line of rogue newline that gets added?

**Comment by agenbite** [comment]
Yeah, you're absolutely right. It is indeed a matter of space. I'm mostly on a laptop, so there's no way I can decrease the text size down to the point where ranger_udisk_menu would work properly. Over ~60 lines text becomes unreadable. And `mount` needs more than that, in my case.

Is there any way this can be solved? Of course, removing my snaps is one way. But I guess that wouldn't be useful for anyone else, right?

**Comment by agenbite** [comment]
Another option, as per [this answer](https://askubuntu.com/a/1107592), would be to add `-e 7` to the call to `lsblk`, in order to remove all loop devices from the list. However, despite it sounds logical since loop devices are not usually mounted by hand, I'm not at all capable to foresee other consequences of such an exclusion in this context.

**Comment by Syphdias** [comment]
Check out #3. I have written a bit about what I have done there as well. In short: `menu.py` only allows you to select "children" (partitions) anyways; so it just doesn't display items without children. A few things:
1. This obviously not a fix
2. Would be nice to have scrolling in the curses interface but I don't want to dive too deep into that right now, but feel free to give it a try.
3. I think the items without "children" should be mountable as well. You could format a raw device if you wanted and the mount it. Also loop devices can be mountable (e.g. iso files)

**Comment by agenbite** [comment]
Well, it looks good to me! I agree on all your remarks, but, for the time being, this is nonetheless a solution to my problem. Thank you, @Syphdias!!
