### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TAforever** [SL-RU/ranger_udisk_menu#6]
I read issue #2 and still don't understand what I have to do to make it work. Regardless of the font size and the terminal window, the menu does not appear.

**Comment by SL-RU** [comment]
Ooh, this is the bug, because of lines is not enough to draw all. I need to add some scrolling

**Comment by TAforever** [comment]
It will be good if you fix it. Thank you for your work, this is a useful thing.

**Comment by TAforever** [comment]
Just installed the new version, everything works fine, thanks.
